# Generated by Django 3.2.25 on 2025-12-31 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'Pending')], default='active', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Deveased',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, max_length=200, null=True, upload_to='%Y-%m-%d', verbose_name='Picture')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Title')),
                ('name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=7, verbose_name='Gender')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('datedied', models.DateField(blank=True, null=True, verbose_name='Date died')),
                ('fatehe_chk', models.BooleanField(default=True, verbose_name='Fatehe')),
                ('salavat_chk', models.BooleanField(default=True, verbose_name='Salavat')),
                ('quran_chk', models.BooleanField(verbose_name='Quran')),
                ('ashora_chk', models.BooleanField(verbose_name='Ashora')),
                ('arbain_chk', models.BooleanField(verbose_name='Arbain')),
                ('ahd_chk', models.BooleanField(verbose_name='Ahd')),
                ('aye_chk', models.BooleanField(verbose_name='Aye')),
                ('sahifeh_chk', models.BooleanField(verbose_name='Sahifeh')),
                ('komil_chk', models.BooleanField(verbose_name='Komil')),
                ('rahman_chk', models.BooleanField(verbose_name='Rahman')),
                ('yasin_chk', models.BooleanField(verbose_name='Yasin')),
                ('molk_chk', models.BooleanField(verbose_name='Molk')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'Pending')], default='active', max_length=60, verbose_name='Status')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citydeads', to='memorial.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Deveased',
                'verbose_name_plural': 'Deveaseds',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'Pending')], default='active', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Ziarat',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('pending', 'Pending')], default='active', max_length=60, verbose_name='Status')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cstate', to='memorial.city', verbose_name='City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zstate', to='memorial.state', verbose_name='State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userziarat', to=settings.AUTH_USER_MODEL, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Ziarat',
                'verbose_name_plural': 'Ziarat',
            },
        ),
        migrations.CreateModel(
            name='Yasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yadead', to='memorial.deveased', verbose_name='Yasin')),
            ],
            options={
                'verbose_name': 'Yasin',
                'verbose_name_plural': 'Yasin',
            },
        ),
        migrations.CreateModel(
            name='Salavat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdead', to='memorial.deveased', verbose_name='Salavat')),
            ],
            options={
                'verbose_name': 'Salavat',
                'verbose_name_plural': 'Salavat',
            },
        ),
        migrations.CreateModel(
            name='Sahifeh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadead', to='memorial.deveased', verbose_name='Sahifeh')),
            ],
            options={
                'verbose_name': 'Sahifeh',
                'verbose_name_plural': 'Sahifeh',
            },
        ),
        migrations.CreateModel(
            name='Rahman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdead', to='memorial.deveased', verbose_name='Rahman')),
            ],
            options={
                'verbose_name': 'Rahman',
                'verbose_name_plural': 'Rahman',
            },
        ),
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deadquran', to='memorial.deveased', verbose_name='Dead')),
            ],
            options={
                'verbose_name': 'Quran',
                'verbose_name_plural': 'Quran',
            },
        ),
        migrations.CreateModel(
            name='Molk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modead', to='memorial.deveased', verbose_name='Molk')),
            ],
            options={
                'verbose_name': 'Molk',
                'verbose_name_plural': 'Molk',
            },
        ),
        migrations.CreateModel(
            name='Komil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdead', to='memorial.deveased', verbose_name='Komil')),
            ],
            options={
                'verbose_name': 'Komil',
                'verbose_name_plural': 'Komil',
            },
        ),
        migrations.CreateModel(
            name='Joz9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j9', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j8', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j7', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j6', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j5', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j4', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j30', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j3', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j29', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j28', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz27',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j27', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j26', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j25', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j24', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j23', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j22', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j21', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j20', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j2', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j19', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j18', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j17', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j16', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j15', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j14', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j13', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j12', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j11', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j10', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j1', to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Fatehe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdead', to='memorial.deveased', verbose_name='Fatehe')),
            ],
            options={
                'verbose_name': 'Fatehe',
                'verbose_name_plural': 'Fatehe',
            },
        ),
        migrations.AddField(
            model_name='deveased',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statedeads', to='memorial.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='deveased',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdeads', to=settings.AUTH_USER_MODEL, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citystate', to='memorial.state', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='Aye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aydead', to='memorial.deveased', verbose_name='Aye')),
            ],
            options={
                'verbose_name': 'Aye',
                'verbose_name_plural': 'Aye',
            },
        ),
        migrations.CreateModel(
            name='Ashora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asdead', to='memorial.deveased', verbose_name='Ashora')),
            ],
            options={
                'verbose_name': 'Ashora',
                'verbose_name_plural': 'Ashora',
            },
        ),
        migrations.CreateModel(
            name='Arbain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ardead', to='memorial.deveased', verbose_name='Arbain')),
            ],
            options={
                'verbose_name': 'Arbain',
                'verbose_name_plural': 'Arbain',
            },
        ),
        migrations.CreateModel(
            name='Ahd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahdead', to='memorial.deveased', verbose_name='Ahd')),
            ],
            options={
                'verbose_name': 'Ahd',
                'verbose_name_plural': 'Ahd',
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'city')},
        ),
    ]
