# Generated by Django 3.1.4 on 2020-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ziarat',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
    ]
