from django.db import models
from django.utils.translation import gettext_lazy as _


class Deveased(models.Model):
    state = models.CharField(max_length=100, verbose_name=_('State'))
    city = models.CharField(max_length=100, verbose_name=_('City'))
    picture = models.ImageField(verbose_name=_('Picture'))
    title = models.CharField(max_length=120, verbose_name=_('Title'))
    fname = models.CharField(max_length=120, verbose_name=_('First Name'))
    lname = models.CharField(max_length=120, verbose_name=_('Last Name'))
    description = models.TextField(verbose_name=_('Description'), null=True)
    address = models.TextField(verbose_name=_('Address'), null=True)
    quran = models.ForeignKey('Quran', on_delete=models.CASCADE)
    fatehe = models.BooleanField(verbose_name=_('Fatehe'), default=True, null=True)
    ashora = models.BooleanField(verbose_name=_('Ashora'), default=False, null=True)
    arbian = models.BooleanField(verbose_name=_('Arbian'), default=False, null=True)
    ahd = models.BooleanField(verbose_name=_('Ahd'), default=False, null=True)
    aye = models.BooleanField(verbose_name=_('Aye'), default=False, null=True)
    sajadie7 = models.BooleanField(verbose_name=_('Sajadie'), default=False, null=True)
    komil = models.BooleanField(verbose_name=_('Komil'), default=False, null=True)
    rabana = models.BooleanField(verbose_name=_('Rabana'), default=False, null=True)
    joz_30 = models.ForeignKey('Quran', to_field='joze30', on_delete=models.CASCADE)


class Quran(models.Model):
    joze1 = models.BooleanField(verbose_name=_('joze 1'), default=False, null=True)
    joze2 = models.BooleanField(verbose_name=_('joze 2'), default=False, null=True)
    joze3 = models.BooleanField(verbose_name=_('joze 3'), default=False, null=True)
    joze4 = models.BooleanField(verbose_name=_('joze 4'), default=False, null=True)
    joze5 = models.BooleanField(verbose_name=_('joze 5'), default=False, null=True)
    joze6 = models.BooleanField(verbose_name=_('joze 6'), default=False, null=True)
    joze7 = models.BooleanField(verbose_name=_('joze 7'), default=False, null=True)
    joze8 = models.BooleanField(verbose_name=_('joze 8'), default=False, null=True)
    joze9 = models.BooleanField(verbose_name=_('joze 9'), default=False, null=True)
    joze10 = models.BooleanField(verbose_name=_('joze 10'), default=False, null=True)
    joze11 = models.BooleanField(verbose_name=_('joze 11'), default=False, null=True)
    joze12 = models.BooleanField(verbose_name=_('joze 12'), default=False, null=True)
    joze13 = models.BooleanField(verbose_name=_('joze 13'), default=False, null=True)
    joze14 = models.BooleanField(verbose_name=_('joze 14'), default=False, null=True)
    joze15 = models.BooleanField(verbose_name=_('joze 15'), default=False, null=True)
    joze16 = models.BooleanField(verbose_name=_('joze 16'), default=False, null=True)
    joze17 = models.BooleanField(verbose_name=_('joze 17'), default=False, null=True)
    joze18 = models.BooleanField(verbose_name=_('joze 18'), default=False, null=True)
    joze19 = models.BooleanField(verbose_name=_('joze 19'), default=False, null=True)
    joze20 = models.BooleanField(verbose_name=_('joze 20'), default=False, null=True)
    joze21 = models.BooleanField(verbose_name=_('joze 21'), default=False, null=True)
    joze22 = models.BooleanField(verbose_name=_('joze 22'), default=False, null=True)
    joze23 = models.BooleanField(verbose_name=_('joze 23'), default=False, null=True)
    joze24 = models.BooleanField(verbose_name=_('joze 24'), default=False, null=True)
    joze25 = models.BooleanField(verbose_name=_('joze 25'), default=False, null=True)
    joze26 = models.BooleanField(verbose_name=_('joze 26'), default=False, null=True)
    joze27 = models.BooleanField(verbose_name=_('joze 27'), default=False, null=True)
    joze28 = models.BooleanField(verbose_name=_('joze 28'), default=False, null=True)
    joze29 = models.BooleanField(verbose_name=_('joze 29'), default=False, null=True)
    joze30 = models.BooleanField(verbose_name=_('joze 30'), default=False, null=True)
