# Generated by Django 3.1.3 on 2020-11-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deveased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('fname', models.CharField(max_length=120, verbose_name='First Name')),
                ('lname', models.CharField(max_length=120, verbose_name='Last Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Deveased',
                'verbose_name_plural': 'Deveaseds',
            },
        ),
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze1', models.BooleanField(default=False, null=True, verbose_name='joze 1')),
                ('joze2', models.BooleanField(default=False, null=True, verbose_name='joze 2')),
                ('joze3', models.BooleanField(default=False, null=True, verbose_name='joze 3')),
                ('joze4', models.BooleanField(default=False, null=True, verbose_name='joze 4')),
                ('joze5', models.BooleanField(default=False, null=True, verbose_name='joze 5')),
                ('joze6', models.BooleanField(default=False, null=True, verbose_name='joze 6')),
                ('joze7', models.BooleanField(default=False, null=True, verbose_name='joze 7')),
                ('joze8', models.BooleanField(default=False, null=True, verbose_name='joze 8')),
                ('joze9', models.BooleanField(default=False, null=True, verbose_name='joze 9')),
                ('joze10', models.BooleanField(default=False, null=True, verbose_name='joze 10')),
                ('joze11', models.BooleanField(default=False, null=True, verbose_name='joze 11')),
                ('joze12', models.BooleanField(default=False, null=True, verbose_name='joze 12')),
                ('joze13', models.BooleanField(default=False, null=True, verbose_name='joze 13')),
                ('joze14', models.BooleanField(default=False, null=True, verbose_name='joze 14')),
                ('joze15', models.BooleanField(default=False, null=True, verbose_name='joze 15')),
                ('joze16', models.BooleanField(default=False, null=True, verbose_name='joze 16')),
                ('joze17', models.BooleanField(default=False, null=True, verbose_name='joze 17')),
                ('joze18', models.BooleanField(default=False, null=True, verbose_name='joze 18')),
                ('joze19', models.BooleanField(default=False, null=True, verbose_name='joze 19')),
                ('joze20', models.BooleanField(default=False, null=True, verbose_name='joze 20')),
                ('joze21', models.BooleanField(default=False, null=True, verbose_name='joze 21')),
                ('joze22', models.BooleanField(default=False, null=True, verbose_name='joze 22')),
                ('joze23', models.BooleanField(default=False, null=True, verbose_name='joze 23')),
                ('joze24', models.BooleanField(default=False, null=True, verbose_name='joze 24')),
                ('joze25', models.BooleanField(default=False, null=True, verbose_name='joze 25')),
                ('joze26', models.BooleanField(default=False, null=True, verbose_name='joze 26')),
                ('joze27', models.BooleanField(default=False, null=True, verbose_name='joze 27')),
                ('joze28', models.BooleanField(default=False, null=True, verbose_name='joze 28')),
                ('joze29', models.BooleanField(default=False, null=True, verbose_name='joze 29')),
                ('joze30', models.BooleanField(default=False, null=True, verbose_name='joze 30')),
            ],
        ),
        migrations.CreateModel(
            name='Sahifeh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('sahifeh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
        migrations.CreateModel(
            name='Rabana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('rabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
        migrations.CreateModel(
            name='Komil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('komil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
        migrations.CreateModel(
            name='Fatehe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('fatehe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
        migrations.CreateModel(
            name='Aye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('aye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
        migrations.CreateModel(
            name='Ashora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('ashora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
        migrations.CreateModel(
            name='Arbain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('arbian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
        migrations.CreateModel(
            name='Ahd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('ahd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
        ),
    ]
