# Generated by Django 3.1.4 on 2020-12-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
            },
        ),
        migrations.CreateModel(
            name='Deveased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Title')),
                ('fname', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=120, null=True, verbose_name='Last Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('quran_chk', models.BooleanField(verbose_name='Quran')),
                ('fatehe_chk', models.BooleanField(verbose_name='Fatehe')),
                ('ashora_chk', models.BooleanField(verbose_name='Ashora')),
                ('arbain_chk', models.BooleanField(verbose_name='Arbain')),
                ('ahd_chk', models.BooleanField(verbose_name='Ahd')),
                ('aye_chk', models.BooleanField(verbose_name='Aye')),
                ('Sahifeh_chk', models.BooleanField(verbose_name='Sahifeh')),
                ('komil_chk', models.BooleanField(verbose_name='Komil')),
                ('rabana_chk', models.BooleanField(verbose_name='Rabana')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorial.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Deveased',
                'verbose_name_plural': 'Deveaseds',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Salavat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('salavat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Salavat')),
            ],
            options={
                'verbose_name': 'Salavat',
                'verbose_name_plural': 'Salavat',
            },
        ),
        migrations.CreateModel(
            name='Sahifeh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Sahifeh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Sahifeh')),
            ],
            options={
                'verbose_name': 'Sahifeh',
                'verbose_name_plural': 'Sahifeh',
            },
        ),
        migrations.CreateModel(
            name='Rabana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Rabana')),
            ],
            options={
                'verbose_name': 'Rabana',
                'verbose_name_plural': 'Rabana',
            },
        ),
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Dead')),
            ],
            options={
                'verbose_name': 'Quran',
                'verbose_name_plural': 'Quran',
            },
        ),
        migrations.CreateModel(
            name='Komil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('komil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Komil')),
            ],
            options={
                'verbose_name': 'Komil',
                'verbose_name_plural': 'Komil',
            },
        ),
        migrations.CreateModel(
            name='Joze9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze29',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Fatehe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fatehe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Fatehe')),
            ],
            options={
                'verbose_name': 'Fatehe',
                'verbose_name_plural': 'Fatehe',
            },
        ),
        migrations.AddField(
            model_name='deveased',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorial.state', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='deveased',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorial.state', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='Aye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('aye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Aye')),
            ],
            options={
                'verbose_name': 'Aye',
                'verbose_name_plural': 'Aye',
            },
        ),
        migrations.CreateModel(
            name='Ashora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ashora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
            options={
                'verbose_name': 'Ashora',
                'verbose_name_plural': 'Ashora',
            },
        ),
        migrations.CreateModel(
            name='Arbain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('arbain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Arbain')),
            ],
            options={
                'verbose_name': 'Arbain',
                'verbose_name_plural': 'Arbain',
            },
        ),
        migrations.CreateModel(
            name='Ahd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ahd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Ahd')),
            ],
            options={
                'verbose_name': 'Ahd',
                'verbose_name_plural': 'Ahd',
            },
        ),
    ]
