# Generated by Django 3.1.3 on 2020-11-30 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deveased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Title')),
                ('fname', models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=120, null=True, verbose_name='Last Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('quran_chk', models.BooleanField(verbose_name='Quran')),
                ('fatehe_chk', models.BooleanField(verbose_name='fatehe')),
                ('ashora_chk', models.BooleanField(verbose_name='ashora')),
                ('arbain_chk', models.BooleanField(verbose_name='arbain')),
                ('ahd_chk', models.BooleanField(verbose_name='ahd')),
                ('aye_chk', models.BooleanField(verbose_name='aye')),
                ('sahife_chk', models.BooleanField(verbose_name='sahife')),
                ('komil_chk', models.BooleanField(verbose_name='komil')),
                ('rabana_chk', models.BooleanField(verbose_name='rabana')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('user_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Deveased',
                'verbose_name_plural': 'Deveaseds',
            },
        ),
        migrations.CreateModel(
            name='Salavat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('salavat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Salavat')),
            ],
            options={
                'verbose_name': 'Salavat',
                'verbose_name_plural': 'Salavat',
            },
        ),
        migrations.CreateModel(
            name='Sahifeh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sahifeh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Sahifeh')),
            ],
            options={
                'verbose_name': 'Sahifeh',
                'verbose_name_plural': 'Sahifeh',
            },
        ),
        migrations.CreateModel(
            name='Rabana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Rabana')),
            ],
            options={
                'verbose_name': 'Rabana',
                'verbose_name_plural': 'Rabana',
            },
        ),
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=60, verbose_name='Status')),
                ('dead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Dead')),
            ],
            options={
                'verbose_name': 'Quran',
                'verbose_name_plural': 'Quran',
            },
        ),
        migrations.CreateModel(
            name='Komil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('komil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Komil')),
            ],
            options={
                'verbose_name': 'Komil',
                'verbose_name_plural': 'Komil',
            },
        ),
        migrations.CreateModel(
            name='Joze9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze9', models.BooleanField(verbose_name='joze 9')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze8', models.BooleanField(verbose_name='joze 8')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze7', models.BooleanField(verbose_name='joze 7')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze6', models.BooleanField(verbose_name='joze 6')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze5', models.BooleanField(verbose_name='joze 5')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze4', models.BooleanField(verbose_name='joze 4')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze30', models.BooleanField(verbose_name='joze 30')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze3', models.BooleanField(verbose_name='joze 3')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze29',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze29', models.BooleanField(verbose_name='joze 29')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze28', models.BooleanField(verbose_name='joze 28')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze27', models.BooleanField(verbose_name='joze 27')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze26', models.BooleanField(verbose_name='joze 26')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze25', models.BooleanField(verbose_name='joze 25')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze24', models.BooleanField(verbose_name='joze 24')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze23', models.BooleanField(verbose_name='joze 23')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze22', models.BooleanField(verbose_name='joze 22')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze21', models.BooleanField(verbose_name='joze 21')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze20', models.BooleanField(verbose_name='joze 20')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze2', models.BooleanField(verbose_name='joze 2')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze19', models.BooleanField(verbose_name='joze 19')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze18', models.BooleanField(verbose_name='joze 18')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze17', models.BooleanField(verbose_name='joze 17')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze16', models.BooleanField(verbose_name='joze 16')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze15', models.BooleanField(verbose_name='joze 15')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze14', models.BooleanField(verbose_name='joze 14')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze13', models.BooleanField(verbose_name='joze 13')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze12', models.BooleanField(verbose_name='joze 12')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze11', models.BooleanField(verbose_name='joze 11')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joze10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze10', models.BooleanField(verbose_name='joze 10')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Joz1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joze1', models.BooleanField(verbose_name='joze 1')),
                ('quran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.quran', verbose_name='Quran')),
            ],
        ),
        migrations.CreateModel(
            name='Fatehe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fatehe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Fatehe')),
            ],
            options={
                'verbose_name': 'Fatehe',
                'verbose_name_plural': 'Fatehe',
            },
        ),
        migrations.CreateModel(
            name='Aye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('aye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Aye')),
            ],
            options={
                'verbose_name': 'Aye',
                'verbose_name_plural': 'Aye',
            },
        ),
        migrations.CreateModel(
            name='Ashora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ashora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased')),
            ],
            options={
                'verbose_name': 'Ashora',
                'verbose_name_plural': 'Ashora',
            },
        ),
        migrations.CreateModel(
            name='Arbain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('arbain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Arbain')),
            ],
            options={
                'verbose_name': 'Arbain',
                'verbose_name_plural': 'Arbain',
            },
        ),
        migrations.CreateModel(
            name='Ahd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='ip')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ahd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorial.deveased', verbose_name='Ahd')),
            ],
            options={
                'verbose_name': 'Ahd',
                'verbose_name_plural': 'Ahd',
            },
        ),
    ]
