# Generated by Django 3.1.3 on 2020-12-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deveased',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorial.state', verbose_name='State'),
        ),
    ]
