# Generated by Django 3.1.3 on 2020-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deveased',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='fname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='lname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Title'),
        ),
    ]
