# Generated by Django 3.1.4 on 2020-12-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deveased',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picture'),
        ),
    ]
