# Generated by Django 3.1.4 on 2020-12-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deveased',
            name='picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='%Y-%m-%d', verbose_name='Picture'),
        ),
    ]
