# Generated by Django 3.1.4 on 2020-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0002_ziarat_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ziarat',
            name='done',
        ),
        migrations.AddField(
            model_name='ziarat',
            name='read',
            field=models.BooleanField(default=False, verbose_name='read'),
        ),
    ]
