# Generated by Django 3.1.4 on 2020-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0002_auto_20201211_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='deveased',
            name='salavat_chk',
            field=models.BooleanField(default=True, verbose_name='Salavat'),
        ),
    ]
