# Generated by Django 3.1.4 on 2020-12-16 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memorial', '0003_deveased_salavat_chk'),
    ]

    operations = [
        migrations.AddField(
            model_name='joz1',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze10',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze11',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze12',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze13',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze14',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze15',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze16',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze17',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze18',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze19',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze2',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze20',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze21',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze22',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze23',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze24',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze25',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze26',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze27',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze28',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze29',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze3',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze30',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze4',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze5',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze6',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze7',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze8',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='joze9',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='quran',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quran',
            name='khatm',
            field=models.IntegerField(default=0, verbose_name='Khatm'),
        ),
        migrations.AlterField(
            model_name='ahd',
            name='ahd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahdead', to='memorial.deveased', verbose_name='Ahd'),
        ),
        migrations.AlterField(
            model_name='arbain',
            name='arbain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ardead', to='memorial.deveased', verbose_name='Arbain'),
        ),
        migrations.AlterField(
            model_name='ashora',
            name='ashora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asdead', to='memorial.deveased', verbose_name='Ashora'),
        ),
        migrations.AlterField(
            model_name='aye',
            name='aye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aydead', to='memorial.deveased', verbose_name='Aye'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citystate', to='memorial.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citydeads', to='memorial.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statedeads', to='memorial.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='deveased',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdeads', to=settings.AUTH_USER_MODEL, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='fatehe',
            name='fatehe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fdead', to='memorial.deveased', verbose_name='Fatehe'),
        ),
        migrations.AlterField(
            model_name='joz1',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j1', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze10',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j10', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze11',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j11', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze12',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j12', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze13',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j13', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze14',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j14', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze15',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j15', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze16',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j16', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze17',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j17', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze18',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j18', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze19',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j19', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze2',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j2', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze20',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j20', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze21',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j21', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze22',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j22', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze23',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j23', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze24',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j24', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze25',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j25', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze26',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j26', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze27',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j27', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze28',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j28', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze29',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j29', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze3',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j3', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze30',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j30', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze4',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j4', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze5',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j5', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze6',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j6', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze7',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j7', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze8',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j8', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='joze9',
            name='quran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j9', to='memorial.quran', verbose_name='Quran'),
        ),
        migrations.AlterField(
            model_name='komil',
            name='komil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdead', to='memorial.deveased', verbose_name='Komil'),
        ),
        migrations.AlterField(
            model_name='quran',
            name='dead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadquran', to='memorial.deveased', verbose_name='Dead'),
        ),
        migrations.AlterField(
            model_name='rabana',
            name='rabana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdead', to='memorial.deveased', verbose_name='Rabana'),
        ),
        migrations.AlterField(
            model_name='sahifeh',
            name='sahifeh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadead', to='memorial.deveased', verbose_name='Sahifeh'),
        ),
        migrations.AlterField(
            model_name='salavat',
            name='salavat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdead', to='memorial.deveased', verbose_name='Salavat'),
        ),
    ]
