# Generated by Django 3.1.4 on 2020-12-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0004_auto_20201216_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quran',
            name='status',
        ),
    ]
