# Generated by Django 3.1.4 on 2020-12-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0005_remove_quran_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='dead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadquran', to='memorial.deveased', unique=True, verbose_name='Dead'),
        ),
    ]
