# Generated by Django 3.1.4 on 2020-12-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0008_auto_20201217_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quran',
            name='khatm',
        ),
    ]
